### ISSUE TITLE
Customize Istio Virtual Service `spec.gateways` via Kservice

### ISSUE THREAD

**Issue by rblaine95** [knative-extensions/net-istio#1124]
> Originally raised in knative/serving#14050

We have multiple Istio Ingress Gateways:
- `istio-internal` for private endpoints (accessible only via VPN)
- `istio-external` for publicly accessible endpoints

It would be great if we could customize the `spec.gateways` config in the resulting Istio Virtual Service via the Kservice manifest.
For example:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: knative-example
spec:
  gateways:
  - istio-system/istio-external
  - istio-system/istio-internal
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
```
Could result in a Virtual Service with the following gateway config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
[...]
  name: hello-ingress
  namespace: knative-example
spec:
  gateways:
  - istio-system/istio-external
  - istio-system/istio-internal
  hosts:
  - hello.example.com
  - hello.knative-example
  - hello.knative-example.svc
  - hello.knative-example.svc.cluster.local
[...]
```
Or:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: knative-example
spec:
  gateways:
  - istio-system/istio-internal
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
```
Results in:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
[...]
  name: hello-ingress
  namespace: knative-example
spec:
  gateways:
  - istio-system/istio-internal
  hosts:
  - hello.example.com
  - hello.knative-example
  - hello.knative-example.svc
  - hello.knative-example.svc.cluster.local
[...]
```

/kind feature-request

**Comment by dprotaso** [comment]
Changing the gateway is really an operator knob vs. app developer setting so you won't see it on the Knative Service spec.

You can change the gateway we set in the VS the controller reconciles via the config map here
https://github.com/knative-sandbox/net-istio/blob/77e1cf889b1757f503744baa22a447c9d82f72c2/config/400-config-istio.yaml#L44-L65

**Comment by dprotaso** [comment]
I wonder if your spec when configuring the operator was off

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-local-gateway:
        selector:
          app: istio-ingressgateway
  config:
    istio:
      local-gateway.istio-system.istio-internal: istio-internal.istio-system.svc.cluster.local
      gateway.istio-system.istio-external: istio-external.istio-system.svc.cluster.local
    domain:
        example.com: ""
    network:
      domain-template: "{{.Name}}.{{.Domain}}"
```

the internal gateway needs a `local-` prefix in the config.

I believe the `knative-local-gateway` override changes knative's gateway (as part of the install) which is not what you want

**Comment by rblaine95** [comment]
Our use case is that we want to use the same host name (for example: `my-app.example.com`) and then be able to access it:
A) Over VPN _only_
B) Over VPN _and_ public internet

For example:
```sh
helm create nginx
helm install nginx ./nginx
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
spec:
  gateways:
  - "istio-system/istio-internal"
  - "istio-system/istio-external"
  hosts:
  - nginx.example.com
  http:
  - name: nginx
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: nginx
EOF
```
The above Virtual Service would make `nginx.example.com` accessible over both VPN and public internet.
Changing the `spec.gateways` to be:
A) Only `istio-system/istio-external`, the result is `404` when on VPN, `200` when not.
B) Only `istio-system/istio-internal`, the result is `200` when on VPN, `404` when not.

This way we can selectively make services/endpoints publicly accessible by adding/removing the `istio-system/istio-external` gateway from the Virtual Service.

**Comment by dprotaso** [comment]
Thanks for the clarification - yeah that makes sense.

I think the only thing to be aware of is that our cluster local gateway would still need to be present so you have L7 load balancing within the cluster.

**Comment by dprotaso** [comment]
Are both ingress gateways pod accessible within the cluster? Our controllers probe them to ensure route programming have propagated.

**Comment by rblaine95** [comment]
@dprotaso 
Each Istio Ingress Gateway is exposed via their own AWS Application (L7) Load Balancer with ACM certificates.
Both Istio Ingress Gateways are, at least as far as I can tell, accessible from within the cluster via their respective K8s services - `istio-(in|ex)ternal.istio-system.svc.cluster.local`.
Pods within the cluster can access the internal/private ALB due to the split-horizon DNS.

**Comment by rblaine95** [comment]
@dprotaso is there a way to have the following behavior:
Kservice with `cluster-local` visibility
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: knative-example
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
          securityContext:
            runAsNonRoot: false
            runAsUser: 1000
```
And a Virtual Service with the following config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
[...]
  name: hello-ingress
  namespace: knative-example
[...]
spec:
  gateways:
  - istio-system/istio-internal
  hosts:
  - hello.example.com # specifically this host value
  - hello.knative-example
  - hello.knative-example.svc
  - hello.knative-example.svc.cluster.local
```
