### ISSUE TITLE
Controller ask for default gateway even if it is overriden with configuration

### ISSUE THREAD

**Issue by stanislav-pimenov** [knative-extensions/net-istio#1407]
Hi guys!

**knative versions:**

1.15.1
1.16.0

**Short description of issue:**

We are using architecture with ingress per namespsace, and using labels to split configurations. And having an issue with validation check within controller. See the steps below to reproduce

Steps to reproduce:

1.
config-istio:

```
data:
  external-gateways: |
    - name: knative-ingress-gateway
      namespace: serving-namespace
      service: no-such-gateway.serving-namespace.svc.cluster.local
    - name: knative-ingress-gateway
      namespace: nmspc1
      service: knative-ingress-svc.nmspc1.svc.cluster.local
      labelSelector:
        matchLabels:
          'ingress-nmspc': nmspc1
    - name: knative-ingress-gateway
      namespace: nmspc2
      service: knative-ingress-svc.nmspc2.svc.cluster.local
      labelSelector:
        matchLabels:
          'ingress-nmspc': nmspc2
  local-gateways: |
    - name: knative-local-gateway
      namespace: serving-namespace
      service: no-such-local-gateway.serving-namespace.svc.cluster.local
    - name: knative-local-gateway
      namespace: nmspc1
      service: knative-local-ingress-svc.nmspc1.svc.cluster.local
      labelSelector:
        matchLabels:
          'ingress-nmspc': nmspc1
    - name: knative-local-gateway
      namespace: nmspc2
      service: knative-local-ingress-svc.nmspc2.svc.cluster.local
      labelSelector:
        matchLabels:
          'ingress-nmspc': nmspc2
```

2. Install Knative Service within namespace **nmspc1**. Lets call it  **hello-world** service. Labeled with _'ingress-nmspc': nmspc1_. 

Everything is up running. Knative is using the correct ingress config defined by label
```
    - name: knative-local-gateway
      namespace: nmspc1
      service: knative-local-ingress-svc.nmspc1.svc.cluster.local
      labelSelector:
        matchLabels:
          'ingress-nmspc': nmspc1
```
4. Uninstall **hello-world** service

**Current behaviour:**
Knative ingress deletion is hanging

Net-istio-controller writes errors like this:

```
{"severity":"ERROR","timestamp":"2025-02-03T10:15:30.242067069Z","logger":"net-istio-controller.istio-ingress-controller","caller":"controller/controller.go:564","message":"Reconcile error","commit":"a85d044-dirty","knative.dev/controller":"istio-ingress-controller","knative.dev/controller":"knative.dev.net-istio.pkg.reconciler.ingress.Reconciler","knative.dev/kind":"networking.internal.knative.dev.Ingress","knative.dev/traceid":"2875f3c6-5f2d-4a35-8de4-cc112b68e389","knative.dev/key":"sk1-tsec01-tsec-tsec-kn-starting/hello","duration":"268.448µs","error":"failed to get Gateway: gateway.networking.istio.io \"knative-ingress-gateway\" not found","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20241021183759-9b9d535af5ad/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20241021183759-9b9d535af5ad/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20241021183759-9b9d535af5ad/controller/controller.go:489"}
```
The only way to pass the validation is to create Gateway called exactly **knative-ingress-gateway** within serving-namespace.

**Expected behavior:**

Since serving namespace doesn't contain any ingress up and running, we don't need **knative-ingress-gateway** to be validated as a part of it.
Seems that useless validation check.

Moreover if we validate all the gateways which are not used, that may affect namespaces witch doesn't use broken gateways

**Comment by pfilaretov42** [comment]
Hi guys, any updates here? I have the same issue.

**Comment by dprotaso** [comment]
Hey do folks have a sample IstioOperator configuration I could use with kind that's representative of your setup?

**Comment by dprotaso** [comment]
Do you have an `IstioOperator` configuration that you're using to setup the namespaces?

**Comment by dprotaso** [comment]
eg. like https://github.com/knative-extensions/net-istio/blob/main/third_party/istio-latest/istio-ci-no-mesh.yaml

**Comment by stanislav-pimenov** [comment]
> Do you have an `IstioOperator` configuration that you're using to setup the namespaces?

no, I don't have such, since istio operator is installed as part of cloud platform. 
To reproduce the issue it's enough to drop the gateway that is installed with net-istio.yaml chart
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: "1.17.0"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
```

**Comment by dprotaso** [comment]
I can't reproduce this deletion 

Here's my IstioOperator configuration that installs 3 ingress gateways

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        clusterDomain: cluster.local
    pilot:
      autoscaleMin: 1
      autoscaleMax: 3
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false

  meshConfig:
    defaultConfig:
      terminationDrainDuration: "20s"

  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: first
        label:
          istio: first
      - name: istio-ingressgateway
        namespace: second
        label:
          istio: second
      - name: istio-ingressgateway
        namespace: third
        label:
          istio: third
```

I setup 3 Istio Gateways
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: first
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: first
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: second
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: second
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: third
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: third
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```


Similarly I created 3 local gateways
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-local-gateway
  namespace: first
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: first
  servers:
    - port:
        number: 8081
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: first
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
    experimental.istio.io/disable-gateway-port-translation: "true"
spec:
  type: ClusterIP
  selector:
    istio: first
  ports:
    - name: http2
      port: 80
      targetPort: 8081
    - name: https
      port: 443
      targetPort: 8444
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-local-gateway
  namespace: second
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: second
  servers:
    - port:
        number: 8081
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: second
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
    experimental.istio.io/disable-gateway-port-translation: "true"
spec:
  type: ClusterIP
  selector:
    istio: second
  ports:
    - name: http2
      port: 80
      targetPort: 8081
    - name: https
      port: 443
      targetPort: 8444
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: knative-local-gateway
  namespace: third
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: third
  servers:
    - port:
        number: 8081
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: third
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
    experimental.istio.io/disable-gateway-port-translation: "true"
spec:
  type: ClusterIP
  selector:
    istio: third
  ports:
    - name: http2
      port: 80
      targetPort: 8081
    - name: https
      port: 443
      targetPort: 8444
```

My config-istio is updated to have
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
data:
  # TODO(nghia): Extract the .svc.cluster.local suffix into its own config.
  external-gateways: |
    - name: knative-ingress-gateway
      namespace: first
      service: istio-ingressgateway.first.svc.cluster.local
    - name: knative-ingress-gateway
      namespace: first
      service: istio-ingressgateway.first.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: first
    - name: knative-ingress-gateway
      namespace: second
      service: istio-ingressgateway.second.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: second
    - name: knative-ingress-gateway
      namespace: third
      service: istio-ingressgateway.third.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: third
  local-gateways: |
    - name: knative-local-gateway
      namespace: first
      service: knative-local-gateway.first.svc.cluster.local
    - name: knative-local-gateway
      namespace: first
      service: knative-local-gateway.first.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: first
    - name: knative-local-gateway
      namespace: second
      service: knative-local-gateway.second.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: second
    - name: knative-local-gateway
      namespace: third
      service: knative-local-gateway.third.svc.cluster.local
      labelSelector:
        matchLabels:
          istio: third
```

I created a Knative service with the correct label - creation and deletion worked without issue.
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: first
  labels:
    istio: first
spec:
  template:
    metadata:
      labels:
        istio: first
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"

```
