### ISSUE TITLE
DomainMapping with PROXY protocol EnvoyFilter

### ISSUE THREAD

**Issue by Marlinc** [knative-extensions/net-istio#463]
Hey there,

I'm using a `EnvoyFilter` on the `istio-ingressgateway` so that I can get the original source address of the client. This worked fine when these connections came in via `istio-ingressgateway` and were then routed to a `cluster-local-gateway` since it didn't have that same `EnvoyFilter`.

The recent merge of these gateways broke using either a the new `DomainMapping` resource as well as the old way of using a `VirtualService` that routes to `cluster-local-gateway`. This is because the Envoy now expects PROXY protocol to be used on internal traffic as well.

I tried limiting the `EnvoyFilter` to port 80 and 443 but that causes `closing connection: no matching filter chain found` errors in Istio (or Envoy).

This is the `EnvoyFilter` I'm currently using:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway

```

**Comment by JRBANCEL** [comment]
> I tried limiting the EnvoyFilter to port 80 and 443 but that causes closing connection: no matching filter chain found errors in Istio (or Envoy).

Did you use a [ListenerMatch](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch)?

If this doesn't work, it is more an Istio issue than Knative I guess.

**Comment by vitobotta** [comment]
Hi @Marlinc how did you solve this eventually? Thanks

**Comment by gecube** [comment]
/reopen

I faced the same issue

**Comment by nak3** [comment]
xref: https://github.com/knative/serving/issues/13123

**Comment by BobyMCbobs** [comment]
I'm also experiencing this.

My EnvoyFilter looks like this
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-ingress
spec:
  configPatches:
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          listener_filters:
            - name: envoy.filters.listener.proxy_protocol
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
            - name: envoy.filters.listener.tls_inspector
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  targetRefs:
    - group: networking.istio.io
      kind: Gateway
      name: istio-ingressgateway
```

Looking into how to filter internal traffic out of the rule.

/reopen
/remove-lifecycle stale
