### ISSUE TITLE
`config.Istio` does not need to take multiple Gateways

### ISSUE THREAD

**Issue by nak3** [knative-extensions/net-istio#718]
The following `IngressGateways` and `LocalGateways` should be a single Gateway:

https://github.com/knative-sandbox/net-istio/blob/d7625fa51eb7e53757e4af95bc09ac86f07c921a/pkg/reconciler/ingress/config/istio.go#L89-L93

Even if it takes multiple Gateways, only one Gateway is used. For example:

https://github.com/knative-sandbox/net-istio/blob/d7625fa51eb7e53757e4af95bc09ac86f07c921a/pkg/reconciler/ingress/ingress.go#L472-L478

Also, this comment line seems strange. LocalGateway should specify the gateway url for private Ingress only.

https://github.com/knative-sandbox/net-istio/blob/d7625fa51eb7e53757e4af95bc09ac86f07c921a/pkg/reconciler/ingress/config/istio.go#L92

**Comment by nak3** [comment]
Re-open this as some users misreads that multiple gateways (e.g. 2 external gw & 1 local gw like below) can be configured in net-istio.

```
data:
  gateway.ns1.gtw1: "ing1.istio-system.svc.cluster.local"
  gateway.ns2.gtw2: "ing2.istio-system.svc.cluster.local"
  local-gateway.ns3.gtw3: "ing3.istio-system.svc.cluster.local"
```
